### ISSUE TITLE
snow only over one image

### ISSUE THREAD

**Issue by skarmoutsosv** [scottschiller/Snowstorm#34]
I currently use java at http://www.skarmoutsos.gr/vaggelis.htm to have a snow effect over an image.
Is it possible to have snow over one image instead of a page, using Snowstorm?

**Comment by scottschiller** [comment]
Sorry I missed this one over the holidays! 😅 

Snowstorm can be constrained to a target element (DOM node), so it's entirely possible to have it snow only within a single `<div>`. The trick is to have your container element be absolute or relatively-positioned, so that snowflakes inside it can be positioned correctly.

**Comment by skarmoutsosv** [comment]
Once you confirmed it can be done, it was just a matter of reading http://www.schillmania.com/projects/snowstorm/#customizing to achieve the needed result.
Thank you
